export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as AboutUs } from './AboutUs'
export { default as Works } from './Works'
export { default as Footer } from './Footer'
export { default as Location } from './Location'
export { default as ContactUs } from './ContactUs'
export { default as MoreInfo } from './MoreInfo'